version: '3.7'
services:
  jenkins:
    container_name: "devops-jenkins"
    image: jenkins/jenkins:lts
    volumes:
      - jenkins-volume:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

  # reviewboard:
  #   image: beanbag/reviewboard:latest
  #   volumes:
  #     - reviewboard-volume:/var/www/reviewboard/data
  #   ports:
  #     - "8000:8000"

  ansible:
    # image: ansible/ansible:ubuntu1404
    container_name: "devops-ansible"
    network_mode: host
    build:
        context: ./ansible
        dockerfile: Dockerfile
    volumes:
      - ansible-volume:/ansible
      - ./ansible/test:/test
    command: /bin/sh -c "while sleep 1000; do :; done"


  # The backend MySQL database server.
  #
  # This is accessed directly by Review Board.
  #
  # In production, this should be shared across all Review Board instances.
  db:
    container_name: "devops-rb-mysql"
    image: mysql:8
    environment:
      # The name of the MySQL database storing Review Board content.
      - MYSQL_DATABASE=reviewboard

      # The MySQL username for Review Board.
      - MYSQL_USER=reviewboard

      # The MySQL password for Review Board.
      #
      # CHANGEME: Use a strong password!
      - MYSQL_PASSWORD=reviewboard123

      # The root MySQL password.
      #
      # CHANGEME: Use a strong password!
      - MYSQL_ROOT_PASSWORD=admin123

    volumes:
      - db_data:/var/lib/mysql

    restart: 'on-failure'


  # The backend memory caching server.
  #
  # This is accessed directly by Review Board.
  #
  # In production, this should be shared across all Review Board instances,
  # and should be configured with at least 2GB of RAM.
  memcached:
    container_name: "devops-rb-memcached"
    image: memcached:alpine
    restart: 'on-failure'

    entrypoint:
      - memcached

      # The amount of RAM available for memcached.
      #
      # CHANGEME: Set this to a suitable amount for your server. We recommend
      #           at least 2GB in production (2048).
      - -m 128


  # The backend Review Board server.
  #
  # This should not be accessed directly. Instead, please access the frontend
  # nginx server.
  reviewboard:
    container_name: "devops-rb"
    image: beanbag/reviewboard:6.0b1
    depends_on:
      - db
      - memcached

    environment:
      - DATABASE_TYPE=mysql

      # The name of your company.
      #
      # CHANGEME: You should use your actual name here. It's used for
      #           internal state and your in-app support page.
      - COMPANY=Docker Compose Test

      # CHANGEME: Set this to the database username above.
      - DATABASE_USERNAME=reviewboard

      # CHANGEME: Set this to the database password above.
      - DATABASE_PASSWORD=reviewboard123

      # CHANGEME: Set this to your accessible domain name.
      - DOMAIN=localhost

    volumes:
      - sitedir:/site

  # The frontend nginx web server.
  #
  # This serves up static media (CSS, JavaScript, and images), and forwards
  # all other requests to the Review Board backend server.
  #
  # This is the server you will access for Review Board.
  nginx:
    container_name: "devops-rb-nginx"
    image: nginx:alpine
    restart: always
    depends_on:
      - reviewboard

    environment:
      # CHANGEME: Set this to your accessible domain name above.
      - NGINX_HOST=localhost

      # The public port used to access this instance.
      #
      # If changed, you will need to change 'ports' below to match.
      - NGINX_PORT=80

    ports:
      - 80:80

    volumes:
      - sitedir:/var/www/reviewboard
      - ./nginx_templates:/etc/nginx/templates


volumes:
  db_data:
  sitedir:
  jenkins-volume:
    driver: local
    driver_opts: { o: bind, type: none, device: ./jenkins }
  reviewboard-volume:
    driver: local
    driver_opts: { o: bind, type: none, device: ./reviewboard }
  ansible-volume:
    driver: local
    driver_opts: { o: bind, type: none, device: ./ansible }
