version: "3"
services:
  app:
    container_name: ${APP_NAME}-server
    ports:
      - 7777:7777
    environment:
      - TEST_PORT=7777

  dapp:
    container_name: ${APP_NAME}-contracts
    links:
      - blockchain
      - ipfs
    environment:
      - BLOCKCHAIN_HOST=blockchain
      - BLOCKCHAIN_PORT=8545
      - TEST_PORT=9999
    volumes:
      - ./client/src/contracts:/workspace/dapp/abis

  blockchain:
    container_name: ${APP_NAME}-blockchain
    image: trufflesuite/ganache-cli:latest
    ports:
      - ${BLOCKCHAIN_PORT}:8545
    volumes:
      # Specify a relative path and let engine create a volume
      - ./blockchain/database:/blockchain/database
    command: >
      --db /blockchain/database
      --accounts 7
      --defaultBalanceEther 111
      --account='0x203b26fd4b754b8ed55eb2f077e9ce4a1ec0a2deb16d25a4612104070aa8bb03,200000000000000000000'
      --account='0x8cc93f9708d101cf8d36c08dfc5b81df715b2e75a575d1de9bb87226d702107a,100000000000000000000'
      --account='0x209f2ccbda1f194b65fb1cdea895d86e2bd4dd44324addf6703ebf235f14314b,50000000000000000000'
      --account='0x76f123556c855218951b889973740018e2ce71a89b9c74b197c0ddb30c31a2f7,40000000000000000000'
      --account='0xac22c2fa4124f28589dd2744e7918e321773d568529540ff3dee03bf3b75e17f,50000000000000000000'
      --account='0x1b2ee170ca73c8ae9d5d3d426e861762df18317ce4c7b27aba052e4876f403e7,60000000000000000000'
      --account='0xcf6673025760a50b5ab86aeb0cd1c7799865fb67dd34a937f03a678ea8813f73,10000000000000000000'

  ipfs:
    container_name: ${APP_NAME}-ipfs
    image: ipfs/go-ipfs:latest
    ports:
      - ${IPFS_SWARM_PORT}:4001
      - ${IPFS_LOCAL_API_PORT}:5001
      - ${IPFS_HTTP_GATEWAY_PORT}:8080
    volumes:
      - ./ipfs/export:/ipfs/export
      - ./ipfs/data:/ipfs/data

  client:
    container_name: ${APP_NAME}-client
    links:
      - app
      - dapp
    environment:
      - APP_HOST=app
      - APP_PORT=7777
      - DAPP_HOST=dapp
      - DAPP_PORT=9999
    volumes:
      - ./client/src/contracts:/workspace/client/src/contracts
