version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: .devcontainer/Dockerfile
    environment:
      - APP_HOST=host.docker.internal
      - APP_PORT=7777
      - DAPP_HOST=host.docker.internal
      - DAPP_PORT=9999
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
