version: "3"
services:
  dapp:
    container_name: dapp
    links:
      - blockchain
    environment:
      - BLOCKCHAIN_HOST=blockchain
      - BLOCKCHAIN_PORT=8545
      - TEST_PORT=9999

  blockchain:
    container_name: blockchain
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545

  web-app:
    container_name: web-app
    links:
      - dapp
    environment:
      - TEST_HOST=dapp
      - TEST_PORT=9999
